services:
  mongodb:
    image: 'mongo:4.4'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=airportdb
    ports:
      - '27017:27017'
